class FsConstants:

    CLUSTER_SIZE = 1024
    CLUSTER_COUNT = 1024
    DISK_SIZE = CLUSTER_SIZE * CLUSTER_COUNT

    SUPERBLOCK_CLUSTER = 0

    FAT_START_CLUSTER = 1
    FAT_END_CLUSTER = 4

    ROOT_DIR_CLUSTER = 5

    CONTENT_START_CLUSTER = 6

    DIRECTORY_ENTRY_SIZE = 32

    FREE = 0
    END = -1